<a href="https://colab.research.google.com/github/i86453966-create/Boston-Housing-dataset/blob/main/Boston_housing_dataset_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
bh=pd.read_csv('/content/HousingData.csv')

In [2]:
bh.shape

(506, 14)

In [3]:
bh.isnull().sum()

CRIM       20
ZN         20
INDUS      20
CHAS       20
NOX         0
RM          0
AGE        20
DIS         0
RAD         0
TAX         0
PTRATIO     0
B           0
LSTAT      20
MEDV        0
dtype: int64

In [4]:
bh['CRIM']=bh['CRIM'].fillna(bh['CRIM'].mean())

In [5]:
bh['ZN']=bh['ZN'].fillna(bh['ZN'].mean())

In [6]:
bh['INDUS']=bh['INDUS'].fillna(bh['INDUS'].mean())

In [7]:
bh['CHAS']=bh['CHAS'].fillna(bh['CHAS'].mean())

In [8]:
bh['AGE']=bh['AGE'].fillna(bh['AGE'].mean())

In [9]:
bh['LSTAT']=bh['LSTAT'].fillna(bh['LSTAT'].mean())

In [10]:
bh.isnull().sum()

CRIM       0
ZN         0
INDUS      0
CHAS       0
NOX        0
RM         0
AGE        0
DIS        0
RAD        0
TAX        0
PTRATIO    0
B          0
LSTAT      0
MEDV       0
dtype: int64

In [11]:
bh.head(30)

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
0,0.00632,18.0,2.31,0.000000,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.980000,24.0
1,0.02731,0.0,7.07,0.000000,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.140000,21.6
2,0.02729,0.0,7.07,0.000000,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.030000,34.7
3,0.03237,0.0,2.18,0.000000,0.458,6.998,45.8,6.0622,3,222,18.7,394.63,2.940000,33.4
4,0.06905,0.0,2.18,0.000000,0.458,7.147,54.2,6.0622,3,222,18.7,396.90,12.715432,36.2
5,0.02985,0.0,2.18,0.000000,0.458,6.430,58.7,6.0622,3,222,18.7,394.12,5.210000,28.7
6,0.08829,12.5,7.87,0.069959,0.524,6.012,66.6,5.5605,5,311,15.2,395.60,12.430000,22.9
7,0.14455,12.5,7.87,0.000000,0.524,6.172,96.1,5.9505,5,311,15.2,396.90,19.150000,27.1
8,0.21124,12.5,7.87,0.000000,0.524,5.631,100.0,6.0821,5,311,15.2,386.63,29.930000,16.5
9,0.17004,12.5,7.87,0.069959,0.524,6.004,85.9,6.5921,5,311,15.2,386.71,17.100000,18.9
10,0.22489,12.5,7.87,0.000000,0.524,6.377,94.3,6.3467,5,311,15.2,392.52,20.450000,15.0
11,0.11747,12.5,7.87,0.000000,0.524,6.009,82.9,6.2267,5,311,15.2,396.90,13.270000,18.9
12,0.09378,12.5,7.87,0.000000,0.524,5.889,39.0,5.4509,5,311,15.2,390.50,15.710000,21.7
13,0.62976,0.0,8.14,0.000000,0.538,5.949,61.8,4.7075,4,307,21.0,396.90,8.260000,20.4
14,0.63796,0.0,8.14,0.069959,0.538,6.096,84.5,4.4619,4,307,21.0,380.02,10.260000,18.2
15,0.62739,0.0,8.14,0.000000,0.538,5.834,56.5,4.4986,4,307,21.0,395.62,8.470000,19.9
16,1.05393,0.0,8.14,0.000000,0.538,5.935,29.3,4.4986,4,307,21.0,386.85,6.580000,23.1
17,0.78420,0.0,8.14,0.000000,0.538,5.990,81.7,4.2579,4,307,21.0,386.75,14.670000,17.5
18,0.80271,0.0,8.14,0.000000,0.538,5.456,36.6,3.7965,4,307,21.0,288.99,11.690000,20.2
19,0.72580,0.0,8.14,0.000000,0.538,5.727,69.5,3.7965,4,307,21.0,390.95,11.280000,18.2
20,1.25179,0.0,8.14,0.000000,0.538,5.570,98.1,3.7979,4,307,21.0,376.57,21.020000,13.6
21,0.85204,0.0,8.14,0.000000,0.538,5.965,89.2,4.0123,4,307,21.0,392.53,13.830000,19.6
22,1.23247,0.0,8.14,0.000000,0.538,6.142,91.7,3.9769,4,307,21.0,396.90,18.720000,15.2
23,0.98843,0.0,8.14,0.000000,0.538,5.813,100.0,4.0952,4,307,21.0,394.54,19.880000,14.5
24,0.75026,0.0,8.14,0.000000,0.538,5.924,94.1,4.3996,4,307,21.0,394.33,16.300000,15.6
25,0.84054,0.0,8.14,0.000000,0.538,5.599,85.7,4.4546,4,307,21.0,303.42,16.510000,13.9
26,0.67191,0.0,8.14,0.000000,0.538,5.813,90.3,4.6820,4,307,21.0,376.88,14.810000,16.6
27,0.95577,0.0,8.14,0.000000,0.538,6.047,88.8,4.4534,4,307,21.0,306.38,17.280000,14.8
28,0.77299,0.0,8.14,0.000000,0.538,6.495,94.4,4.4547,4,307,21.0,387.94,12.800000,18.4
29,1.00245,0.0,8.14,0.000000,0.538,6.674,87.3,4.2390,4,307,21.0,380.23,11.980000,21.0

In [12]:
bh.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 14 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   CRIM     506 non-null    float64
 1   ZN       506 non-null    float64
 2   INDUS    506 non-null    float64
 3   CHAS     506 non-null    float64
 4   NOX      506 non-null    float64
 5   RM       506 non-null    float64
 6   AGE      506 non-null    float64
 7   DIS      506 non-null    float64
 8   RAD      506 non-null    int64
 9   TAX      506 non-null    int64
 10  PTRATIO  506 non-null    float64
 11  B        506 non-null    float64
 12  LSTAT    506 non-null    float64
 13  MEDV     506 non-null    float64
dtypes: float64(12), int64(2)
memory usage: 55.5 KB

In [13]:
bh['CHAS'].value_counts()

CHAS
0.000000    452
1.000000     34
0.069959     20
Name: count, dtype: int64

In [14]:
bh=pd.get_dummies(bh,columns=['CHAS'])

In [15]:
bh.head()

,CRIM,ZN,INDUS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV,CHAS_0.0,CHAS_0.06995884773662552,CHAS_1.0
0,0.00632,18.0,2.31,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.980000,24.0,True,False,False
1,0.02731,0.0,7.07,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.140000,21.6,True,False,False
2,0.02729,0.0,7.07,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.030000,34.7,True,False,False
3,0.03237,0.0,2.18,0.458,6.998,45.8,6.0622,3,222,18.7,394.63,2.940000,33.4,True,False,False
4,0.06905,0.0,2.18,0.458,7.147,54.2,6.0622,3,222,18.7,396.90,12.715432,36.2,True,False,False

In [16]:
x=bh.drop(['MEDV'],axis=1)
y=bh['MEDV']

In [17]:
from sklearn.model_selection import train_test_split
x_train , x_test , y_train , y_test =train_test_split(x,y,test_size=0.2,random_state=42)

In [18]:
from sklearn.metrics import r2_score

In [19]:
import numpy as np
from sklearn.metrics import mean_squared_error

In [21]:
from sklearn.ensemble import GradientBoostingRegressor
model=GradientBoostingRegressor(random_state=42)
model.fit(x_train,y_train)
result=model.predict(x_test)
print(r2_score(y_test,result))
mse=mean_squared_error(y_test,result)
print(np.sqrt(mse))

0.8960013871757208
2.761632075753408

In [22]:
import joblib as jb
jb.dump(model,"Boston housing dataset.pkl")

['Boston housing dataset.pkl']

In [23]:
pip install streamlit

Collecting streamlit
  Downloading streamlit-1.55.0-py3-none-any.whl.metadata (9.8 kB)
Requirement already satisfied: altair!=5.4.0,!=5.4.1,<7,>=4.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (5.5.0)
Requirement already satisfied: blinker<2,>=1.5.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (1.9.0)
Requirement already satisfied: cachetools<8,>=5.5 in /usr/local/lib/python3.12/dist-packages (from streamlit) (6.2.6)
Requirement already satisfied: click<9,>=7.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (8.3.1)
Requirement already satisfied: gitpython!=3.1.19,<4,>=3.0.7 in /usr/local/lib/python3.12/dist-packages (from streamlit) (3.1.46)
Requirement already satisfied: numpy<3,>=1.23 in /usr/local/lib/python3.12/dist-packages (from streamlit) (2.0.2)
Requirement already satisfied: packaging>=20 in /usr/local/lib/python3.12/dist-packages (from streamlit) (26.0)
Requirement already satisfied: pandas<3,>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (2.2.2)
Requirement already satisfied: pillow<13,>=7.1.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (11.3.0)
Collecting pydeck<1,>=0.8.0b4 (from streamlit)
  Downloading pydeck-0.9.1-py2.py3-none-any.whl.metadata (4.1 kB)
Requirement already satisfied: protobuf<7,>=3.20 in /usr/local/lib/python3.12/dist-packages (from streamlit) (5.29.6)
Requirement already satisfied: pyarrow>=7.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (18.1.0)
Requirement already satisfied: requests<3,>=2.27 in /usr/local/lib/python3.12/dist-packages (from streamlit) (2.32.4)
Requirement already satisfied: tenacity<10,>=8.1.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (9.1.4)
Requirement already satisfied: toml<2,>=0.10.1 in /usr/local/lib/python3.12/dist-packages (from streamlit) (0.10.2)
Requirement already satisfied: tornado!=6.5.0,<7,>=6.0.3 in /usr/local/lib/python3.12/dist-packages (from streamlit) (6.5.1)
Requirement already satisfied: typing-extensions<5,>=4.10.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (4.15.0)
Requirement already satisfied: watchdog<7,>=2.1.5 in /usr/local/lib/python3.12/dist-packages (from streamlit) (6.0.0)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (3.1.6)
Requirement already satisfied: jsonschema>=3.0 in /usr/local/lib/python3.12/dist-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (4.26.0)
Requirement already satisfied: narwhals>=1.14.2 in /usr/local/lib/python3.12/dist-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (2.18.0)
Requirement already satisfied: gitdb<5,>=4.0.1 in /usr/local/lib/python3.12/dist-packages (from gitpython!=3.1.19,<4,>=3.0.7->streamlit) (4.0.12)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas<3,>=1.4.0->streamlit) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas<3,>=1.4.0->streamlit) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas<3,>=1.4.0->streamlit) (2025.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.27->streamlit) (3.4.5)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.27->streamlit) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.27->streamlit) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.27->streamlit) (2026.2.25)
Requirement already satisfied: smmap<6,>=3.0.1 in /usr/local/lib/python3.12/dist-packages (from gitdb<5,>=4.0.1->gitpython!=3.1.19,<4,>=3.0.7->streamlit) (5.0.3)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (3.0.3)
Requirement already satisfied: attrs>=22.2.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (25.4.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (0.30.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas<3,>=1.4.0->streamlit) (1.17.0)
Downloading streamlit-1.55.0-py3-none-any.whl (9.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.1/9.1 MB 61.6 MB/s eta 0:00:00
Downloading pydeck-0.9.1-py2.py3-none-any.whl (6.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.9/6.9 MB 45.5 MB/s eta 0:00:00
Installing collected packages: pydeck, streamlit
Successfully installed pydeck-0.9.1 streamlit-1.55.0